#!/usr/bin/env bash
# factors
# Maira Wangui

check_factor() {
    factors=($(factor "$1" | awk '{for(i=2;i<=NF;++i) print $i}'))
    num1=${factors[-1]}
    num2=$(IFS='*'; echo "${factors[*]::${#factors[@]}-1}")
    echo "$1=$num1*$num2"
}

if [ $# -ne 1 ]; then
    echo 'Usage: factors <file>'
    exit 1
else
    while read i; do
        check_factor "$i"
    done < "$1"
fi
